<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0"
         xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0
         http://maven.apache.org/xsd/maven-4.0.0.xsd">
    <modelVersion>4.0.0</modelVersion>

    <groupId>com.hkt.iot</groupId>
    <artifactId>hkt-iot-platform</artifactId>
    <version>1.0.0-SNAPSHOT</version>
    <packaging>pom</packaging>

    <name>HKT IoT Platform</name>
    <description>华宽通智能体平台</description>

    <modules>
        <module>hkt-iot-parent</module>
        <module>hkt-iot-common</module>
        <module>hkt-iot-domain</module>
        <module>hkt-iot-user-service</module>
        <module>hkt-iot-device-service</module>
        <module>hkt-iot-space-service</module>
        <module>hkt-iot-rule-service</module>
        <module>hkt-iot-scene-service</module>
        <module>hkt-iot-smart-apps-service</module>
        <module>hkt-iot-notification-service</module>
        <module>hkt-iot-notification-service-client</module>
        <module>hkt-iot-gateway</module>
    </modules>

</project>
